require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/oils", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Oil. As you add validations to Oil, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # OilsController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    {}
  }

  describe "GET /index" do
    it "renders a successful response" do
      Oil.create! valid_attributes
      get oils_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      oil = Oil.create! valid_attributes
      get oil_url(oil), as: :json
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Oil" do
        expect {
          post oils_url,
               params: { oil: valid_attributes }, headers: valid_headers, as: :json
        }.to change(Oil, :count).by(1)
      end

      it "renders a JSON response with the new oil" do
        post oils_url,
             params: { oil: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Oil" do
        expect {
          post oils_url,
               params: { oil: invalid_attributes }, as: :json
        }.to change(Oil, :count).by(0)
      end

      it "renders a JSON response with errors for the new oil" do
        post oils_url,
             params: { oil: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq("application/json")
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested oil" do
        oil = Oil.create! valid_attributes
        patch oil_url(oil),
              params: { oil: new_attributes }, headers: valid_headers, as: :json
        oil.reload
        skip("Add assertions for updated state")
      end

      it "renders a JSON response with the oil" do
        oil = Oil.create! valid_attributes
        patch oil_url(oil),
              params: { oil: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "renders a JSON response with errors for the oil" do
        oil = Oil.create! valid_attributes
        patch oil_url(oil),
              params: { oil: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq("application/json")
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested oil" do
      oil = Oil.create! valid_attributes
      expect {
        delete oil_url(oil), headers: valid_headers, as: :json
      }.to change(Oil, :count).by(-1)
    end
  end
end
